import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import { Expense } from '../context/ExpenseContext';
import { formatCurrency } from './utils';

export const generatePDFReport = (expenses: Expense[], user: any, budget: any, dateRange?: { start: string; end: string }) => {
  const doc = new jsPDF();
  const themeColor = [16, 185, 129]; // Emerald Green

  // Header
  doc.setFillColor(themeColor[0], themeColor[1], themeColor[2]);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('FINDO', 20, 25);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('SMART FINANCIAL DECISIONS', 20, 32);
  
  doc.setFontSize(12);
  doc.text(`REPORT FOR: ${user?.name || 'Valued User'}`, 190, 25, { align: 'right' });
  doc.text(`DATE: ${format(new Date(), 'PP')}`, 190, 32, { align: 'right' });

  // Summary Information
  let yPos = 55;
  doc.setTextColor(30, 41, 59); // Slate 800
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Transaction Summary', 20, yPos);
  
  const totalSpent = expenses.reduce((sum, e) => sum + e.amount, 0);
  const currency = budget?.currency || 'INR';
  
  yPos += 12;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Transactions: ${expenses.length}`, 20, yPos);
  doc.text(`Total Expenditure: ${formatCurrency(totalSpent, currency)}`, 20, yPos + 7);
  
  if (dateRange?.start || dateRange?.end) {
    const rangeText = `${dateRange.start ? format(new Date(dateRange.start), 'MMM d, yyyy') : 'Beginning'} - ${dateRange.end ? format(new Date(dateRange.end), 'MMM d, yyyy') : 'Today'}`;
    doc.text(`Filtered Period: ${rangeText}`, 190, yPos, { align: 'right' });
  }

  // Transactions Table
  const tableData = expenses.map(e => [
    format(new Date(e.date), 'MMM d, yyyy'),
    e.merchant,
    e.category,
    e.paymentMethod || 'N/A',
    formatCurrency(e.amount, currency)
  ]);

  autoTable(doc, {
    startY: yPos + 20,
    head: [['Date', 'Merchant', 'Category', 'Payment', 'Amount']],
    body: tableData,
    headStyles: { 
      fillColor: [16, 185, 129], 
      textColor: [255, 255, 255], 
      fontStyle: 'bold',
      halign: 'left'
    },
    alternateRowStyles: { 
      fillColor: [248, 250, 252] 
    },
    styles: { 
      fontSize: 9, 
      cellPadding: 4,
      font: 'helvetica'
    },
    columnStyles: {
      4: { halign: 'right' } // Amount column right aligned
    }
  });

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // Slate 400
    doc.text(
      `Generated by Findo Expense Manager • Page ${i} of ${pageCount}`,
      105,
      285,
      { align: 'center' }
    );
  }

  // Save the PDF
  const filename = `Findo_Report_${format(new Date(), 'yyyy-MM-dd')}.pdf`;
  doc.save(filename);
};
